# Generated by Django 3.2.6 on 2021-08-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=100)),
            ],
        ),
    ]
