# Generated by Django 3.2.6 on 2021-08-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('one', '1 of n choises'), ('many', 'm of n choises'), ('descri', 'Descriptive')], default='one', max_length=10),
        ),
    ]
