# Generated by Django 3.2.6 on 2021-08-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210811_0611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='choice',
            name='letter',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple', '1 of n choises'), ('ture/false', 'True/False'), ('descriptive', 'Descriptive')], default='one', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'letter')},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='number',
        ),
    ]
