# Generated by Django 3.2.6 on 2021-08-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210811_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.FloatField(null=True, unique=True),
        ),
    ]
