# Generated by Django 3.2.6 on 2021-08-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_question_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['question', 'letter']},
        ),
    ]
