# Generated by Django 3.2.6 on 2021-08-12 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0011_alter_choice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=1000, null=True)),
                ('rand', models.FloatField(default=web.models.randomFloat)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'question'],
            },
        ),
    ]
