# Generated by Django 3.2.6 on 2021-08-14 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0013_auto_20210814_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dicom',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='questionnaire_item',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.question'),
        ),
        migrations.AlterField(
            model_name='questionnaire_item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('7bf0e9b8-1036-4362-992b-fd86995a4fcc')),
        ),
    ]
