# Generated by Django 3.2.6 on 2021-08-14 16:47

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0014_auto_20210814_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('fedba65d-14cf-4786-a77c-ee7358c54af1')),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire_item',
            unique_together={('user', 'question', 'dicom')},
        ),
    ]
