# Generated by Django 3.2.6 on 2021-08-14 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210814_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('6828ed73-21e4-41a7-b1be-f4862d6e682c')),
        ),
    ]
