# Generated by Django 3.2.6 on 2021-08-14 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('8a213caa-2e9d-4c3b-a7a6-b2821b80d92b')),
        ),
    ]
