# Generated by Django 3.2.6 on 2021-08-14 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.UUID('8a6318f2-2403-458d-b810-28ab4d5f5882')),
        ),
    ]
