# Generated by Django 3.2.6 on 2021-08-14 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20210814_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tokenn',
            field=models.UUIDField(default=uuid.UUID('41c82b21-6ea0-48f4-aed0-5dc510a0dddb')),
        ),
    ]
