# Generated by Django 3.2.6 on 2021-08-14 17:10

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_token_tokenn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='tokenn',
        ),
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=web.models.randomToken),
        ),
    ]
