# Generated by Django 3.2.6 on 2021-08-14 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0022_auto_20210814_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire_item',
            name='dicomFolder',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire_item',
            unique_together={('user', 'question', 'dicomFolder')},
        ),
        migrations.RemoveField(
            model_name='questionnaire_item',
            name='dicom',
        ),
    ]
