# Generated by Django 3.2.6 on 2021-08-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20210815_0042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaire_item',
            unique_together=set(),
        ),
    ]
