# Generated by Django 3.2.6 on 2021-08-14 21:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0027_alter_questionnaire_item_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire_item',
            old_name='dicomFolder',
            new_name='dicom',
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire_item',
            unique_together={('user', 'question', 'dicom')},
        ),
    ]
