# Generated by Django 3.2.6 on 2021-08-18 07:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0028_auto_20210815_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire_item',
            options={'ordering': ['user', 'dicom', 'question']},
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire_item',
            unique_together={('user', 'dicom', 'question')},
        ),
    ]
