# Generated by Django 3.2.6 on 2021-08-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20210818_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multi_sequence',
            field=models.BooleanField(default=False),
        ),
    ]
