# Generated by Django 4.1.3 on 2023-01-01 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0031_alter_questionnaire_item_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=1000, null=True)),
                ('rand', models.FloatField(default=web.models.randomFloat)),
                ('drawing', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['user', 'dicom', 'question__number'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple', '1 of n choices'), ('ture/false', 'True/False'), ('descriptive', 'Descriptive')], default='one', max_length=15),
        ),
        migrations.DeleteModel(
            name='Questionnaire_Item',
        ),
        migrations.AddField(
            model_name='questionnaireitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.question'),
        ),
        migrations.AddField(
            model_name='questionnaireitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireitem',
            unique_together={('user', 'dicom', 'question')},
        ),
    ]
