# Generated by Django 4.1.3 on 2023-01-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_questionnaireitem_alter_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireitem',
            name='drawing',
        ),
        migrations.AddField(
            model_name='question',
            name='drawable_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaireitem',
            name='drawing_state',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
